services:
  # Backend Web Service
  - type: web
    name: banana-sales-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: banana-sales-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: banana-sales-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: banana-sales-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: banana-sales-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: banana-sales-db
          property: password

  # Frontend Static Site
  - type: web
    name: banana-sales-frontend
    env: static
    plan: free
    buildCommand: |
      # Update API endpoint in app.html to use production backend
      sed -i 's/localhost:3000/banana-sales-backend.onrender.com/g' app.html
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /app.html

databases:
  # PostgreSQL Database
  - name: banana-sales-db
    plan: free
    databaseName: banana_sales
    user: banana_sales_user
    postgresMajorVersion: 15